import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { cn } from "@/lib/utils";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

const maisonNeue = localFont({
  src: [
    {
      path: "../../assets/fonts/Maison_Neue_Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../assets/fonts/Maison_Neue_Book.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../assets/fonts/Maison_Neue_Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-sans",
});

const maisonNeueMono = localFont({
  src: "../../assets/fonts/Maison_Neue_Mono.ttf",
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html
      lang={locale}
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        maisonNeue.variable,
        maisonNeueMono.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
